### ISSUE TITLE
Install instructions site is down

### ISSUE THREAD

**Issue by alager** [mjholtkamp/submin#6]
The link in the instructions: `https://ssl.supermind.nl/collab/projects/submin/browser/INSTALL` gives a server error:
```
Internal Server Error

TracError: IOError: [Errno 13] Permission denied: u'/var/lib/submin/collab/trac/submin/log/trac.log'
```

**Comment by mjholtkamp** [comment]
Thanks for letting me know. It was a problem with setting permissions during logrotate. I fixed that configuration and changed permissions. Should be accessible now!
